# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'WalletApp' do
  # Pods for WalletApp
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'
  pod 'SwiftQRScanner', :git => ‘https://github.com/vinodiOS/SwiftQRScanner’
end
